# Generated by Django 5.0.6 on 2026-03-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='inquiry_type',
            field=models.CharField(choices=[('consultation', 'Free Consultation'), ('general', 'General Message'), ('franchise', 'Franchise Inquiry')], default='general', max_length=30),
        ),
    ]
